### PR TITLE
Deprecate project in favor of gulp-jsdoc3

### PR DESCRIPTION
**Pull request by mlucool**
Deprecating re: https://github.com/jsBoot/gulp-jsdoc/issues/28

### CODE REVIEW

**Comment by mlucool** [comment]
@dmp42 or @indexzero could you please merge this?

**Comment by indexzero** [comment]
This is @dmp42's call.

**Comment by mlucool** [comment]
Given the update in https://github.com/jsBoot/gulp-jsdoc/issues/28 it seems like this is both fine and up to you also

**Comment by indexzero** [comment]
I'm really not comfortable merging it until I give @dmp42 at least another couple of days. Everyone is just decompressing from the holiday and I wouldn't want to do something big and inappropriate like this if he doesn't want it.

It's the same courtesy I would want if I were him. Almost there :smile_cat:

**Comment by mlucool** [comment]
Totally fine, just wanted to keep this moving

**Comment by dmp42** [comment]
Thank you all :)

I'm fine with this. Unless someone is willing to keep working on this implementation here, users should indeed be warned.

**Comment by mlucool** [comment]
:+1: Thanks for all your work on this project! I wouldn't have ever experimented with jsdoc without it.

**Pull request merged**
