### PR TITLE
Complete rewrite to support jsdoc 3.4 with a minimal wrapper

### PR DESCRIPTION
**Pull request by mlucool**
This is a re-write that tries to be as minimal of a wrapper as possible. jsdoc supports all options, even CLI to be in the config file that so that all this accepts. The exception here is the template engine is chosen. Gulp is used simply to gather file names, and even output comes from the config.

I would also like to consider moving this repo to 1.0 and then follow semver even if jsdoc doesn't.

Fix for: https://github.com/jsBoot/gulp-jsdoc/issues/28

### CODE REVIEW

**Comment by lukeapage** [comment]
Nice, I've just finished fixing everything I plan to ink-docstrap and bumping version numbers.. (was checking dependents), so.1.0.2 is out now.

**Comment by mlucool** [comment]
Great! Are there any breaking changes or if I bump the version will it just work? Also, how big were the changes? More precisely, should I be worried it is not yet stable enough given it was released yesterday?

**Comment by lukeapage** [comment]
nope,  i bumped to 1.0 to start following semver..  initial development is
long over.

**Comment by mlucool** [comment]
Updated

**Comment by lukeapage** [comment]
@dmp42 @indexzero

**Comment by mlucool** [comment]
Released here: https://www.npmjs.com/package/gulp-jsdoc3

**Comment by indexzero** [comment]
Cool. I am fine with this, but I honestly don't know if this is good or not. If I don't hear from @dmp42 in a couple days I'm just going to merge this and call it a breaking change.

**Comment by mlucool** [comment]
Released as [gulp-jsdoc3](https://www.npmjs.com/package/gulp-jsdoc3) per https://github.com/jsBoot/gulp-jsdoc/issues/28

**Comment by dmp42** [comment]
I'm happy to see progress on jsdoc from and for people who use it :)

The two packages have a different approach wrt integration. I'm pretty sure that @mlucool 's binary wrapping approach will prove more resilient to changes in jsdoc - at the cost of proper io streams integration.

**Pull request closed without merging**
